server:
  port: 8081
spring:
  application:
    name: zuul_server
  zipkin:
    base-url: http://localhost:9411

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
zuul:
  routes:
    zipkin_server:
      path: /zipkin_server/**
      serviceId: zipkin_server
  ignored-services: '*'