server:
  port: 8081
<<<<<<< HEAD

spring:
  application:
    name: zuul-server
=======
spring:
  application:
    name: zuul_server
  zipkin:
    base-url: http://localhost:9411
>>>>>>> 1f928a1d30a9d70d31fe1f06a3e043248d2a6984

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
<<<<<<< HEAD

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    oauth:
      path: /oauth2/**
      serviceId: oauth2-server
      sensitiveHeaders: "*"
    login:
      path: /login-server/**
      serviceId: login-server
      sensitiveHeaders: "*"
    customer:
      path: /customer-server/**
      serviceId: customer-server
      sensitiveHeaders: "*"
    business:
      path: /business-server/**
      serviceId: business-server
      sensitiveHeaders: "*"
  add-host-header: true
=======
zuul:
  routes:
    zipkin_server:
      path: /zipkin_server/**
      serviceId: zipkin_server
  ignored-services: '*'
>>>>>>> 1f928a1d30a9d70d31fe1f06a3e043248d2a6984
