server:
  port: 8080

eureka:
  client:
    #不在本缓存注册表信息
    fetch-registry: false
    #不通过eureka服务注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
<<<<<<< HEAD
    name: eureka-server
=======
    name: eureka_server
>>>>>>> 1f928a1d30a9d70d31fe1f06a3e043248d2a6984
